import os
import subprocess
import logging
import pandas as pd

from powerpwn.copilot_studio.modules.path_utils import get_project_file_path

def get_project_file_path(*args):
    """
    Utility function to construct absolute file paths relative to the script's directory,
    handling parent directories.
    """
    return os.path.abspath(os.path.join(os.path.dirname(__file__), *args))

def query_using_pup_from_file(links_file_path):
    """
    Reads bot URLs from a text file and executes the Puppeteer JavaScript code for each bot URL.
    The function calls a JavaScript file.

    :param links_file_path: Path to the text file containing bot URLs, one per line.
    """
    pup_path = get_project_file_path('../../tools/pup_query_webchat', 'query_chat.js')
    bots_has_knowledge_path = get_project_file_path('../final_results', 'chat_exists_output.xlsx')

    # Read bot URLs from the text file
    with open(links_file_path, 'r') as f:
        open_bots = [line.strip() for line in f if line.strip()]

    # Delete the existing Excel file to start fresh
    if os.path.exists(bots_has_knowledge_path):
        os.remove(bots_has_knowledge_path)
        logging.debug(f"Deleted existing file: {bots_has_knowledge_path}")

    for bot_url in open_bots:
        try:
            # Construct the shell command
            command = f'node "{pup_path}" "{bot_url}"'
            logging.debug(f"Running command: `{command}`")
            print(f"Processing bot URL: {bot_url}")
            # Run the command
            subprocess.run(command, shell=True, check=True)  # nosec
        except subprocess.CalledProcessError as e:
            logging.error(f"Error occurred while running Puppeteer: {e}")

    if os.path.exists(bots_has_knowledge_path):
        # Read the output Excel file and create a dictionary
        return parse_chatbot_results(bots_has_knowledge_path)

    return {}

def parse_chatbot_results(file_path):
    """
    Parses the output Excel file generated by query_chat.js and returns a dictionary.

    :param file_path: Path to the output Excel file.
    :return: Dictionary with bot URL as key and knowledge info as value.
    """
    # Read the Excel file into a DataFrame
    df = pd.read_excel(file_path)

    bot_results = {}
    for _, row in df.iterrows():
        url = str(row.get('URL', '')).strip()
        has_knowledge = str(row.get('Has Knowledge', '')).strip()
        titles_str = row.get('Titles', '')
        titles = []

        if pd.notnull(titles_str) and titles_str:
            # Split titles by semicolon and strip whitespace
            titles = [title.strip() for title in titles_str.split(';')]

        bot_results[url] = {
            'has_knowledge': has_knowledge,
            'titles': titles
        }

    return bot_results

def main():
    # Update the path to be __dirname, '../../final_results/bot_links.txt'
    links_file_path = get_project_file_path('../final_results/chat_exists_output.txt')

    # Process the bots and parse the results
    bot_results = query_using_pup_from_file(links_file_path)

    # Now you can work with bot_results as needed
    print("\nBot Results:")
    for url, data in bot_results.items():
        print(f"URL: {url}")
        print(f"  Has Knowledge: {data['has_knowledge']}")
        print(f"  Titles: {', '.join(data['titles'])}")

    # If needed, you can save bot_results to a file or perform further processing

if __name__ == "__main__":
    # Configure logging if needed
    logging.basicConfig(level=logging.INFO)
    main()

